app1/urls.py
from django.urls import path
from . import views

app_name = "app1"

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.login_user, name="login"),
    path("register/", views.register, name="register"),
    path("logout/", views.logout_user, name="logout"),
    path("create_quiz/", views.create_quiz, name="create_quiz"),
    path("quiz_details/<int:quiz_id>/", views.quiz_details, name="quiz_details"),
    path("take_quiz/<int:quiz_id>/", views.takequizview, name="take_quiz"),
    path("results/<int:quiz_id>/", views.resultsview, name="results"),
    path("user-profile/", views.user_profile_view, name="user_profile"),
    path("add_question/<int:quiz_id>", views.add_question, name="add_question"),
    path("allquizzes/", views.list_all_quizzes, name="allquizzes"),
    path("archived/", views.list_archived_quizzes, name="archived"),
    path("my_quizzes/", views.my_quizzes, name="my_quizzes"),
]

finalproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('app1.urls')),
    path('admin/', admin.site.urls),
]

app1/models.py
from django.db import models
from django.contrib.auth.models import User, AbstractUser


# Create your models here.
class User(AbstractUser):
    profile_picture = models.ImageField(upload_to='profile_pictures/', null=True, blank=True)

    def __str__(self):
        return self.username


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Quiz(models.Model):
    title = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    instructions = models.TextField(blank=True, null=True)
    status = models.BooleanField(verbose_name="is_open", default=False)
    archived = models.BooleanField(verbose_name="is_archived", default=False)
    # points = models.PositiveIntegerField(default=0)

    auther = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)

    difficulty_level = models.CharField(
        max_length=20,
        choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
        default="medium",
    )
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True
    )
    time_limit = models.IntegerField(default=10)  # in minutes

    def __str__(self):
        return self.title


class Question(models.Model):
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    points = models.PositiveIntegerField(default=0)
    question_text = models.TextField()
    category = models.ForeignKey(
        Category, on_delete=models.SET_NULL, null=True, blank=True
    )
    difficulty_level = models.CharField(
        max_length=20,
        choices=[("easy", "Easy"), ("medium", "Medium"), ("hard", "Hard")],
        default="medium",
    )
    time_limit = models.IntegerField(default=30)  # in seconds
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=255)
    is_correct = models.BooleanField(default=False)

    def __str__(self):
        if self.is_correct:
            return self.choice_text + " Correct"
        else:
            return self.choice_text


class UserAnswer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, on_delete=models.CASCADE, null=True, blank=True)
    is_correct = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.choice


class Score(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE)
    score = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} has score: {self.score} in {self.quiz.title}"

app1/views.py
from django.core.files.storage import default_storage
from PIL import Image
import math
from django.shortcuts import render, redirect, get_object_or_404
from django.http import JsonResponse
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError
from django.db.models import Avg, Sum
from django.urls import reverse
from django.contrib.auth.decorators import login_required


from .models import (
    User,
    Category,
    Quiz,
    Question,
    Choice,
    UserAnswer,
    Score,
)


# Create your views here.
def index(request):
    if not request.user.is_authenticated:
        return redirect("app1:login")

    availablequizzes = Quiz.objects.filter(status=True)
    return render(
        request,
        "app1/index.html",
        {
            "available_quizzes": availablequizzes,
        },
    )


def list_all_quizzes(request):
    allquizzes = Quiz.objects.filter(archived=False)
    return render(
        request,
        "app1/all_quizzes.html",
        {
            "allquizzes": allquizzes,
        },
    )


def list_archived_quizzes(request):
    archived_quizzes = Quiz.objects.filter(archived=True)
    return render(
        request,
        "app1/archived.html",
        {
            "quizlist": archived_quizzes,
        },
    )


def my_quizzes(request):
    if not request.user.is_authenticated:
        return redirect("app1:login")

    user = request.user

    # Created Quizzes
    created_quizzes = Quiz.objects.filter(auther=user)

    # Participated Quizzes (assuming participation through answered questions)
    participated_quizzes = Quiz.objects.filter(score__user=user).distinct()

    context = {
        "created_quizzes": created_quizzes,
        "participated_quizzes": participated_quizzes,
    }

    return render(request, "app1/my_quizzes.html", context)


def create_quiz(request):
    if not request.user.is_authenticated:
        return redirect("app1:login")

    categories = Category.objects.all()
    if request.method == "POST":
        quiztitle = request.POST.get("quiz-title")
        quizdescription = request.POST.get("quiz-description")
        timelimit = request.POST.get("time-limit")
        difficulty = request.POST.get("difficulty-level")
        categoryname = request.POST.get("category")

        category = get_object_or_404(Category, name=categoryname)

        newquiz = Quiz.objects.create(
            title=quiztitle,
            description=quizdescription,
            difficulty_level=difficulty,
            category=category,
            time_limit=timelimit,
        )
        newquiz.save()

        return redirect(
            reverse(
                "app1:add_question",
                kwargs={
                    "quiz_id": newquiz.id,
                },
            )
        )
    else:
        return render(
            request,
            "app1/create_quiz.html",
            {
                "categories": categories,
            },
        )


def add_question(request, quiz_id):
    newquiz = get_object_or_404(Quiz, pk=quiz_id)
    return render(
        request,
        "app1/add_questions.html",
        {
            "quiz": newquiz,
        },
    )


def quiz_details(request, quiz_id):
    curr_quiz = get_object_or_404(Quiz, pk=quiz_id)
    total_points = 0
    num_questions = 0
    for question in curr_quiz.question_set.all():
        total_points += question.points
        num_questions += 1
    if curr_quiz is not None:
        return render(request, "app1/quiz_details.html", {
            "quiz": curr_quiz,
            'points': total_points,
            'num_questions': num_questions,
        },)


@login_required
def takequizview(request, quiz_id):
    if request.method == "GET":
        quiz = get_object_or_404(Quiz, pk=quiz_id)
        questions = quiz.question_set.all()
        return render(request, "app1/take_quiz.html", {
                "quiz": quiz,
                "questions": questions,
        },)
    return redirect('app1:results')


def resultsview(request, quiz_id):
    score = 0
    quiz = get_object_or_404(Quiz, pk=quiz_id)
    all_questions = quiz.question_set.all()
    num_questions = all_questions.count()
    questions_answered = 0
    total_score = 0
    correct_questions = 0

    for question in all_questions:
        total_score += question.points
        selected_choice = request.POST.get(f"option-{question.id}")
        try:
            choice = Choice.objects.get(pk=selected_choice, question=question)
            if choice.is_correct == True:
                score += question.points
                correct_questions += 1
            questions_answered += 1
        except Choice.DoesNotExist:
            pass

    user = request.user
    # create a Score entry
    Score.objects.create(
        user=user,
        quiz=quiz,
        score=score,
    ).save()

    percentage = math.ceil((score / total_score) * 100) 
    context = {
        "score": score,
        "total_questions": num_questions,
        'questions_answered': questions_answered,
        'total_score': total_score,
        'correct_questions': correct_questions,
        "percentage": percentage,
    }
    return render(request, "app1/results.html", context)


def user_profile_view(request):
    user = request.user

    if request.method == 'POST':
        profile_picture = request.FILES.get('profile_picture')
        if profile_picture:
            # Save the original image to the media directory
            image_path = default_storage.save(profile_picture.name, profile_picture)
            image = Image.open(default_storage.path(image_path))

            # Resize the image to 400x400 pixels
            image = image.resize((400, 400), Image.ANTIALIAS)

            # Save the resized image back to the media directory
            resized_image_path = default_storage.save(f"resized_{image_path}", image)

            # Update the user's profile picture field
            user.profile_picture = resized_image_path
            user.save()

    else:
        scorelist = Score.objects.filter(user=user, score__isnull=False)

        total_score_so_far = 0
        total_quiz_attemps = scorelist.count()
        total_points = 0

        total_contribution = Quiz.objects.filter(auther=user).count()

        for scoreobj in scorelist:
            total_score_so_far += scoreobj.score
            
            for question in scoreobj.quiz.question_set.all():
                    total_points += question.points

        average_score = 0
        if total_points is not 0:
            average_score = (total_score_so_far/total_points) * 100
        average_score = math.ceil(average_score)

        context = {
            'user': user,
            'total_attempts': total_quiz_attemps,
            'average_score': average_score,
            'quizzes_created': total_contribution,
        }

        return render(request, 'app1/user_profile.html', context)


def login_user(request):
    if request.method == "POST":

        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect("app1:index")
        return render(
            request,
            "app1/login.html",
            {
                "err_message": "Invalid username or password",
            },
        )
    return render(request, "app1/login.html")


def register(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        firstname = request.POST['firstname']
        lastname = request.POST['lastname']
        email = request.POST['email']

        # Attempt to create new user
        try:
            user = User.objects.create_user(
                username=username,
                password=password,
                first_name=firstname,
                last_name=lastname,
                email=email
            )
            user.save()
        except IntegrityError:
            return render(request, "app1/register.html", {
                "err_message": "Username already taken."},
            )
        login(request, user)
        return redirect("app1:index")
    return render(request, "app1/register.html")


def logout_user(request):
    logout(request)
    return redirect("app1:login")

app1/templates/app1/all_quizzes.html
{% extends "app1/base.html" %}

{% block body %}

<main>

  <section class="py-2 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">All Quizzes</h1>
        <p class="lead text-body-secondary">Below collection includes all open and closed quizzes</p>
        <p>
          <a href="{% url 'app1:index' %}" class="btn btn-success my-2">Available Quizzes</a>
          <a href="{% url 'app1:archived' %}" class="btn btn-secondary my-2">Go to Archive</a>
        </p>
      </div>
    </div>
  </section>

  <div class="album py-2 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for quiz in allquizzes %}
        {% if quiz.status %}
        <!-- show is green -->
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <h4 class="card-title">{{ quiz.title }}</h4>
              <p class="card-text">{{ quiz.description|truncatechars:100 }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{% url 'app1:quiz_details' quiz.id %}" class="btn btn-sm btn-outline-secondary">View</a>
                </div>
                <small class="text-body-secondary">{{ quiz.time_limit }} mins</small>
              </div>
            </div>
          </div>
        </div>
        {% else %}
        <!-- show it red -->
        <div class="col">
          <div class="card shadow-sm bg-danger bg-opacity-10">
            <div class="card-body">
              <h4 class="card-title">{{ quiz.title }}</h4>
              <p class="card-text">{{ quiz.description|truncatechars:100 }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{% url 'app1:quiz_details' quiz.id %}"
                    class="disabled btn btn-sm btn-outline-secondary">View</a>
                </div>
                <div>
                  <small class="text-danger me-2">Closed</small>
                  <small class="text-body-secondary">{{ quiz.time_limit }} mins</small>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endif %}
        {% empty %}
        <h3>No quizzes are open at the time</h3>
        {% endfor %}
      </div>
    </div>
  </div>
  </div>

</main>

{% endblock body %}

app1/templates/app1/archived.html
{% extends "app1/base.html" %}

{% block body %}

<main>

  <section class="py-2 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">All Quizzes</h1>
        <p class="lead text-body-secondary">All archived quizzes are listed here.</p>
        <p>
          <a href="{% url 'app1:index' %}" class="btn btn-success my-2">Available Quizzes</a>
          <a href="{% url 'app1:allquizzes' %}" class="btn btn-primary my-2">All Quizzes</a>
        </p>
      </div>
    </div>
  </section>

  <div class="album py-2 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for quiz in quizlist %}
        <div class="col">
          <div class="card shadow-sm bg-secondary bg-opacity-10">
            <div class="card-body">
              <h4 class="card-title">{{ quiz.title }}</h4>
              <p class="card-text">{{ quiz.description|truncatechars:100 }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{% url 'app1:quiz_details' quiz.id %}"
                    class="disabled btn btn-sm btn-outline-secondary">View</a>
                </div>
                <div>
                  <small class="text-danger me-2">Closed</small>
                  <small class="text-body-secondary">{{ quiz.time_limit }} mins</small>
                </div>
              </div>
            </div>
          </div>
        </div>
        {% empty %}
        <h3>No quizzes are open at the time</h3>
        {% endfor %}
      </div>
    </div>
  </div>
  </div>

</main>

{% endblock body %}

app1/templates/app1/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" class="h-100" data-bs-theme="light">

<head>
    <script></script>

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" href="{% static 'app1/images/favicon/key-72.png' %}" type="image/x-icon">
        <title>{% block title %}{% endblock %}</title>

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

        <link rel="stylesheet" href="{% static 'app1/css/style.css' %}">

        {% block css %}{% endblock %}

    </head>

<body class='d-flex flex-column h-100 py-4 bg-body-tertiary'>
    <header>
        <!-- Fixed navbar -->
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
            <div class="container-fluid">
                <a class="navbar-brand text-success" href="{% url 'app1:index' %}">qWiz</a>
                <button class="navbar-toggler collapsed" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <i class="bi bi-three-dots"></i>
                    <!-- <span class="navbar-toggler-icon"></span> -->
                </button>
                <div class="navbar-collapse collapse" id="navbarCollapse">
                    <ul class="navbar-nav me-auto mb-2 mb-md-0">
                        <li class="nav-item">
                            <a class="nav-link" aria-current="page" href="{% url 'app1:index' %}"><i
                                    class="bi bi-house-door-fill"></i> Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'app1:my_quizzes' %}"><i
                                    class="bi bi-bookmark-fill"></i>Myquizzes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'app1:create_quiz' %}"><i
                                    class="bi bi-file-earmark-plus-fill"></i> Contribute</a>
                        </li>
                        {% if user.is_authenticated %}
                        <li class="nav-item">

                        </li>

                        <div class="dropdown">
                            <button class="btn btn-secondary rounded-pill p-1" data-bs-toggle="dropdown"
                                aria-expanded="false">
                                <span
                                    class="badge d-flex align-items-center p-1  text-body bg-transparent rounded-pill"><img
                                        class="rounded-circle me-1" width="24" height="24"
                                        src="{% static 'app1/images/favicon/key-72.png' %}" alt="">
                                    <div class="col px-3 ">
                                        <div class="row text-light">
                                            {{ user.firstname }} {{ user.lastname }}
                                        </div>
                                        <div class="row text-light">
                                            @{{ user.username }}
                                        </div>
                                    </div>
                                </span>
                            </button>

                            <ul class="dropdown-menu"
                                style="position: absolute; inset: 0px auto auto 0px; margin: 0px; transform: translate(0px, 40px);"
                                data-popper-placement="bottom-start">
                                <li>
                                    <h6 class="dropdown-header">Dropdown header</h6>
                                </li>
                                <li><a class="dropdown-item" href="{% url 'app1:user_profile' %}"><i
                                            class="bi bi-person-fill"></i> Profile</a></li>
                                <li><a class="dropdown-item" href="#"><i class="bi bi-speedometer"></i> Dashboard</a>
                                </li>
                                <li><a class="dropdown-item" href="#"><i class="bi bi-gear-fill"></i> Settings</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item text-danger" href="{% url 'app1:logout' %}"><i
                                            class="bi bi-door-closed-fill"></i> Logout</a></li>
                            </ul>
                        </div>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    {% block header %}
    {% endblock %}


    <main class="flex-shrink-0">
        <div class="container">
            <!-- <h1 class="mt-5">Sticky footer with fixed navbar</h1>
        <p class="lead">Pin a footer to the bottom of the viewport in desktop browsers with this custom HTML and CSS. A fixed navbar has been added with <code class="small">padding-top: 60px;</code> on the <code class="small">main &gt; .container</code>.</p> -->
            {% block body %}
            {% endblock %}
        </div>
    </main>

    <div class="footer mt-auto container">
        <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
            
            <a href="#" class="col-md-4 d-flex align-items-center justify-content-start p-2 mb-3 mb-md-0 me-md-auto link-body-emphasis text-decoration-none">
                <i class="bi bi-key"></i>
            </a>

            <ul class="nav justify-content-end">
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Home</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">Features</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">FAQs</a></li>
            <li class="nav-item"><a href="#" class="nav-link px-2 text-body-secondary">About</a></li>
            </ul>
        </footer>
    </div>

    {% block footer %}
    {% endblock %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    {% block script %}{% endblock %}
</body>

</html>

app1/templates/app1/create_quiz.html
{% extends 'app1/base.html' %}
{% load static %}

{% block body %}

<div class="col-lg-8 mx-auto p-4 py-md-5">
  <div>
    <form class="needs-validation" action="{% url 'app1:create_quiz' %}" method="post">
      {% csrf_token %}

      <div class="form-floating my-2">
        <input class="form-control" type="text" name="quiz-title" id="quiz-title" placeholder="Quiz title" value=""
          required="true">
        <label for="quiz-title">Title</label>
      </div>

      <div class="form-floating my-2">
        <textarea style="resize: none; overflow-y: hidden;" class="form-control" placeholder="Quiz description"
          name="quiz-description" id="quiz_description"></textarea>
        <label for="quiz_description">Quiz description</label>
      </div>

      <div class="input-group my-2">
        <div class="form-floating">
          <input class="form-control" type="number" min="1" id="time-limit" name="time-limit" placeholder="Time Limit"
            value="1" required="true">
          <label for="time-limit">Duration</label>
        </div>
        <div class="form-floating">
          <select class="form-control" type="text" name="difficulty-level" id="difficulty-level"
            placeholder="difficulty-level" required="true">
            <option value="none">...</option>
            <option value="easy">Easy</option>
            <option value="medium">Medium</option>
            <option value="hard">Hard</option>
          </select>
          <label for="difficulty-level">Difficulty</label>
        </div>
        <div class="form-floating">
          <select class="form-control" type="text" id="category" placeholder="Category" required="true" name="category">
            <option value="none">...</option>
            {% for category in categories %}
            <option value="{{category}}">{{ category | title }}</option>
            {% endfor %}
          </select>
          <label for="category">Category</label>
        </div>
      </div>

  </div>

  <hr class="my-4">

  <button class="w-100 btn btn-primary btn-lg" type="submit">Next &rightarrow;</button>
  </form>
</div>
</div>

<script src="{% static 'app1/js/adjust-text-area.js' %}"></script>

{% endblock %}

<!-- {% block script %}
{% endblock %} -->

app1/templates/app1/index.html
{% extends "app1/base.html" %}
{% load static %}

{% block body %}


<main>
  <div class="container marketing">

    <div class="row featurette">
      <div class="col-md-7">
        <h2 class="featurette-heading fw-normal lh-1">Ace Your Quizzes with Our Interactive Platform. <span class="text-body-secondary">Its really simple.</span></h2>
        <p class="lead">Our innovative quiz app offers a fun and engaging way to test your knowledge and improve your skills. With a wide range of subjects and difficulty levels, there's something for everyone. Track your progress, compete with friends, and unlock achievements as you master new topics.</p>
      </div>
      <div class="col-md-5">
        <img class="rounded-circle bd-placeholder-img bd-placeholder-img-lg featurette-image img-fluid mx-auto" width="300" height="300" role="img" aria-label="Placeholder: 500x500" preserveAspectRatio="xMidYMid slice" focusable="false" src="{% static 'app1/images/key-400.png' %}" alt="key-400">
      </div>
    </div>
    <hr class="featurette-divider">
  </div>

    
  <section class="py-2 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">Available Quizzes</h1>
        <p class="lead text-body-secondary">A collection of quizzes on various topics.</p>
        <p>
          <a href="{% url 'app1:archived' %}" class="btn btn-secondary my-2">Go to Archive</a>
        </p>
      </div>
    </div>
  </section>

  <div class="album py-2 bg-body-tertiary">
    <div class="container">
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
        {% for quiz in available_quizzes %}
        <div class="col">
          <div class="card shadow-sm">
            <div class="card-body">
              <h4 class="card-title">{{ quiz.title }}</h4>
              <p class="card-text">{{ quiz.description|truncatechars:100 }}</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <a href="{% url 'app1:quiz_details' quiz.id %}" class="btn btn-sm btn-outline-secondary">View</a>
                </div>
                <small class="text-body-secondary">{{ quiz.time_limit }} mins</small>
              </div>
            </div>
          </div>
        </div>
        {% empty %}
        <h3>No quizzes are open at the time</h3>
        {% endfor %}
      </div>
    </div>
  </div>
  </div>

</main>

{% endblock body %}

app1/templates/app1/login.html
{% extends "app1/base.html" %}
{% load static %}

{% block title %}Login - Enter the world of quizzes{% endblock %}

{% block css %}
<link rel="stylesheet" href="{% static 'app1/css/login.css' %}">
{% endblock %}

{% block body %}

<div class="modal modal-sheet position-static d-block bg-body-secondary py-md-5" tabindex="-1" role="dialog"
  id="modalSignin">
  <div class="modal-dialog" role="document">
    <div class="modal-content rounded-4 shadow">
      <div class="modal-header p-5 pb-4 border-bottom-0">
        <h1 class="fw-bold mb-0 fs-2">Please Login</h1>
      </div>

      <div class="modal-body p-5 pt-0">
        {% if err_message %}<small class="text-warning">{{ err_message }}</small>{% endif %}
        <form action="{% url 'app1:login' %}" method="post">
          {% csrf_token %}

          <div class="form-floating mb-3">
            <input type="text" class="form-control rounded-3" id="floatingInput" placeholder="username" name="username">
            <label for="floatingInput">Username</label>
          </div>
          <div class="form-floating mb-3">
            <input type="password" class="form-control rounded-3" id="floatingPassword" placeholder="Password"
              name="password">
            <label for="floatingPassword">Password</label>
          </div>
          <button class="w-100 mb-2 btn btn-lg rounded-3 btn-primary" type="submit">Sign in</button>
          <p class="mt-2 mb-3 text-body-secondary">New to the qWiz? Register <a
              href="{% url 'app1:register' %}">here</a></p>



          <hr class="my-4">

          <small class="text-warning">[to be implemented]</small>
          <h2 class="fs-5 fw-bold mb-3">Or use a third-party</h2>
          <button class="w-100 py-2 mb-2 btn btn-outline-secondary rounded-3" type="submit">
            <svg class="bi me-1" width="16" height="16">
              <use xlink:href="#twitter"></use>
            </svg>
            Log in with Twitter
          </button>
          <button class="w-100 py-2 mb-2 btn btn-outline-primary rounded-3" type="submit">
            <svg class="bi me-1" width="16" height="16">
              <use xlink:href="#facebook"></use>
            </svg>
            Log in with Facebook
          </button>
          <button class="w-100 py-2 mb-2 btn btn-outline-secondary rounded-3" type="submit">
            <svg class="bi me-1" width="16" height="16">
              <use xlink:href="#github"></use>
            </svg>
            Log in with GitHub
          </button>
        </form>
      </div>
    </div>
  </div>
</div>
{% endblock body %}

app1/templates/app1/my_quizzes.html
{% extends 'app1/base.html' %}

{% block body %}

<h1>My Quizzes</h1>

<h2>Created Quizzes</h2>
<ul>
    {% for quiz in created_quizzes %}
    <li><a href="{% url 'app1:quiz_details' quiz.id %}">{{ quiz.title }}</a></li>
    {% endfor %}
</ul>

<h2>Participated Quizzes</h2>
<ul>
    {% for quiz in participated_quizzes %}
    <li><a href="{% url 'app1:quiz_details' quiz.id %}">{{ quiz.title }}</a></li>
    {% endfor %}
</ul>

{% endblock %}